version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pupuk-api-app
    image: pupuk-api-app
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    environment:
      - ACCEPT_EULA=Y
      - LANG=en_US.UTF-8
    restart: unless-stopped
